name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ESW_TS_VERSION: "0.1.0-RC1"
    steps:
      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: 11
          apps: sbt sbtn
      - uses: coursier/cache-action@v5

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g junit-merge
      - run: npm install -g junit-viewer

      - name: Configure ntp time
        run: |
          sudo apt-get update -y
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          sudo apt-get install ntp -y
          sudo ntptime -T 37

      - name: Unit and Component Tests
        run: |
          sbt -DenableCoverage=true -DgenerateStoryReport=true csw-time/test:test
          sbt -DenableCoverage=true -DgenerateStoryReport=true -DdisableTimeTests test:test

      - name: Coverage Report
        run: |
          sbt -DenableCoverage=true coverageReport
          sbtn coverageAggregate

      - uses: actions/upload-artifact@v1
        with:
          name: Coverage Report
          path: target/scala-2.13/scoverage-report

      - name: Delete js targets
        continue-on-error: true
        run: find . -type d -regex ".*js/target.*" | xargs rm -rf

      - name: Multi-Jvm Tests
        run: sbt -DgenerateStoryReport=true integration/multi-jvm:test
